# -*- coding: utf-8 -*-
from . import op_academic_plan_stages
from . import calendar_event
from . import res_company
from . import op_course
from . import op_course_plan
from . import hr_employee
from . import op_academic_plan
from . import op_area
from . import op_batch
from . import op_faculty
from . import op_intake_year
from . import op_specialization
from . import op_student
from . import op_student_course
from . import op_subject
from . import op_subject_registration
from . import op_program
from . import op_assessment_type
from . import op_badge_student_wizard
from . import op_board_affiliation
from . import res_config_settings
from . import op_course_category
from . import wizard_course_allocation
from . import op_gamification_badge
from . import op_badge_student
from . import op_marks_line
from . import ir_module_module
from . import onboarding_onboarding
from . import onboarding_onboarding_step
from . import op_department
from . import publisher_warranty_contract
from . import op_section
from . import op_subject_faculty
from . import op_topics
from . import res_users
from . import website
from . import website_configurator_feature
