# -*- coding: utf-8 -*-
# AUTO-GENERATED SKELETON — reconstructed from Odoo database metadata
# Real Python source lives on the server filesystem, not in the database.
# This skeleton reflects field definitions, mixins, ACL and record rules.

from odoo import models, fields, api
from odoo.exceptions import ValidationError, UserError


class ResConfigSettings(models.TransientModel):
    """Config Settings

    Enhanced configuration interface for exchange rate management
    """

    _name = 'res.config.settings'
    _description = 'Config Settings'

    # ── Fields ──────────────────────────────────────────────
    access_token = fields.Char(string='Access Token')
    account_cash_basis_base_account_id = fields.Many2one('account.account', string='Base Tax Received Account', store=False, help='Account that will be set on lines created in cash basis journal entry and used to keep track of the tax base amount.')
    account_default_credit_limit = fields.Monetary(string='Default Credit Limit', store=False, help='This is the default credit limit that will be used on partners that do not have a specific limit on them.')
    account_discount_expense_allocation_id = fields.Many2one('account.account', string='Customer Invoices Discounts Account', store=False)
    account_discount_income_allocation_id = fields.Many2one('account.account', string='Vendor Bills Discounts Account', store=False)
    account_fiscal_country_id = fields.Many2one('res.country', string='Fiscal Country Code', store=False, help='The country to use the tax reports from for this company')
    account_journal_early_pay_discount_gain_account_id = fields.Many2one('account.account', string='Early Discount Gain', store=False, help='Account for the difference amount after the income discount has been granted')
    account_journal_early_pay_discount_loss_account_id = fields.Many2one('account.account', string='Early Discount Loss', store=False, help='Account for the difference amount after the expense discount has been granted')
    account_journal_suspense_account_id = fields.Many2one('account.account', string='Bank Suspense', store=False, help='Bank Transactions are posted immediately after import or synchronization. Their counterparty is the bank suspense accoun')
    account_on_checkout = fields.Selection(string='Customer Accounts', required=True, store=False, selection=[])
    account_price_include = fields.Selection(string='Default Sales Price Include', required=True, store=False, selection=[], help='Default on whether the sales price used on the product and invoices with this Company includes its taxes.')
    account_storno = fields.Boolean(string='Storno accounting', store=False)
    account_use_credit_limit = fields.Boolean(string='Sales Credit Limit', store=False, help='Enable the use of credit limit on partners.')
    active_provider_id = fields.Many2one('payment.provider', string='Active Provider', store=False)
    active_user_count = fields.Integer(string='Number of Active Users', store=False)
    add_to_cart_action = fields.Selection(string='Add To Cart Action', store=False, selection=[])
    alias_domain_id = fields.Many2one('mail.alias.domain', string='Alias Domain', store=False, help='If you have setup a catch-all email domain redirected to the Odoo server, enter the domain name here.')
    anglo_saxon_accounting = fields.Boolean(string='Use anglo-saxon accounting', store=False, help='Record the cost of a good as an expense when this good is invoiced to a final customer.')
    annual_inventory_day = fields.Integer(string='Day of the month', store=False, help='Day of the month when the annual inventory should occur. If zero or negative, then the first day of the month will be se')
    annual_inventory_month = fields.Selection(string='Annual Inventory Month', store=False, selection=[], help='Annual inventory month for products not in a location with a cyclic inventory date. Set to no month if no automatic annu')
    app_login_details_show = fields.Boolean(string='Replace Login URL')
    app_login_name = fields.Char(string='Login Page Name')
    app_login_url = fields.Char(string='Login Page URL')
    app_ribbon_name = fields.Char(string='Show Demo Ribbon')
    app_ribbon_name_show = fields.Boolean(string='Show Ribbon')
    app_show_lang = fields.Boolean(string='Show Quick Language Switcher', help='When enable,User can quick switch language in user menu')
    app_system_name = fields.Char(string='System Name', help='Setup System Name,which replace Odoo')
    attendance_subject_generic = fields.Selection(string='Attendance Subject Generic', selection=[], help='Subject-specific attendance will be gathered during a particular session, whereas general attendance will be collected b')
    auth_signup_reset_password = fields.Boolean(string='Enable password reset from Login page')
    auth_signup_template_user_id = fields.Many2one('res.users', string='Template user for new users created through signup')
    auth_signup_uninvited = fields.Selection(string='Customer Account', store=False, selection=[])
    auth_totp_enforce = fields.Boolean(string='Enforce two-factor authentication')
    auth_totp_policy = fields.Selection(string='Two-factor authentication enforcing policy', selection=[])
    automatic_email = fields.Boolean(string='Automatic Email')
    automatic_invoice = fields.Boolean(string='Automatic Invoice', help='The invoice is generated automatically and available in the customer portal when the transaction is confirmed by the pay')
    autopost_bills = fields.Boolean(string='Auto-validate bills', store=False)
    barcode_nomenclature_id = fields.Many2one('barcode.nomenclature', string='Nomenclature', store=False)
    barcode_separator = fields.Char(string='Separator', help='Character(s) used to separate data contained within an aggregate barcode (i.e. a barcode containing multiple barcode enc')
    cart_abandoned_delay = fields.Float(string='Abandoned Delay', store=False)
    cart_recovery_mail_template = fields.Many2one('mail.template', string='Cart Recovery Email', store=False)
    cdn_activated = fields.Boolean(string='Content Delivery Network (CDN)', store=False)
    cdn_filters = fields.Text(string='CDN Filters', store=False, help='URL matching those filters will be rewritten using the CDN Base URL')
    cdn_url = fields.Char(string='CDN Base URL', store=False)
    channel_id = fields.Many2one('im_livechat.channel', string='Website Live Channel', store=False)
    chart_template = fields.Selection(string='Chart Template', selection=[])
    client_id = fields.Char(string='Client ID')
    client_secret = fields.Char(string='Client Secret')
    company_count = fields.Integer(string='Number of Companies', store=False)
    company_country_code = fields.Char(string='Company Country Code', store=False, help='The ISO country code in two chars.  You can use this field for quick search.')
    company_country_group_codes = fields.Json(string='Country Group Codes', store=False)
    company_currency_id = fields.Many2one('res.currency', string='Company Currency', store=False)
    company_expense_allowed_payment_method_line_ids = fields.Many2many('account.payment.method.line', string='Payment methods available for expenses paid by company')
    company_id = fields.Many2one('res.company', string='Company', required=True)
    company_informations = fields.Text(string='Company Informations', store=False)
    company_name = fields.Char(string='Company Name', store=False)
    company_so_template_id = fields.Many2one('sale.order.template', string='Default Template', store=False)
    confirmation_email_template_id = fields.Many2one('mail.template', string='Confirmation Email Template', store=False)
    contract_expiration_notice_period = fields.Integer(string='Contract Expiry Notice Period', store=False)
    country_code = fields.Char(string='Country Code', store=False, help='The ISO country code in two chars.  You can use this field for quick search.')
    crm_auto_assignment_action = fields.Selection(string='Auto Assignment Action', selection=[], help='Manual assign allow to trigger assignment from team form view using an action button. Automatic configures a cron runnin')
    crm_auto_assignment_interval_number = fields.Integer(string='Repeat every', help='Number of interval type between each cron run (e.g. each 2 days or each 4 days)')
    crm_auto_assignment_interval_type = fields.Selection(string='Auto Assignment Interval Unit', selection=[], help='Interval type between each cron run (e.g. each 2 days or each 2 hours)')
    crm_auto_assignment_run_datetime = fields.Datetime(string='Auto Assignment Next Execution Date')
    crm_use_auto_assignment = fields.Boolean(string='Rule-Based Assignment')
    currency_exchange_journal_id = fields.Many2one('account.journal', string='Currency Exchange Journal', store=False, help='The accounting journal where automatic exchange differences will be registered')
    currency_id = fields.Many2one('res.currency', string='Currency', required=True, store=False, help='Main currency of the company.')
    days_to_purchase = fields.Float(string='Days to Purchase', store=False, help='Days needed to confirm a PO, define when a PO should be validated')
    default_allow_out_of_stock_order = fields.Boolean(string='Continue selling when out-of-stock')
    default_available_threshold = fields.Float(string='Show Threshold')
    default_invoice_policy = fields.Selection(string='Invoicing Policy', selection=[])
    default_picking_policy = fields.Selection(string='Picking Policy', required=True, selection=[])
    default_show_availability = fields.Boolean(string='Show availability Qty')
    delay_alert_contract = fields.Integer(string='Delay alert contract outdated')
    digest_emails = fields.Boolean(string='Digest Emails')
    digest_id = fields.Many2one('digest.digest', string='Digest Email')
    display_account_storno = fields.Boolean(string='Display Account Storno', store=False)
    display_invoice_amount_total_words = fields.Boolean(string='Total amount of invoice in letters', store=False)
    display_invoice_tax_company_currency = fields.Boolean(string='Taxes in company currency', store=False)
    documents_binary_max_size = fields.Integer(string='Size', help='Defines the maximum upload size in MB. Default (25MB)')
    documents_forbidden_extensions = fields.Char(string='Extensions', help='Defines a list of forbidden file extensions. (Example: \'exe,msi\')')
    downpayment_account_id = fields.Many2one('account.account', string='Downpayment Account', store=False, help='This account will be used on Downpayment invoices.')
    ecommerce_access = fields.Selection(string='Ecommerce Access', store=False, selection=[])
    email_primary_color = fields.Char(string='Email Button Text', store=False)
    email_secondary_color = fields.Char(string='Email Button Color', store=False)
    enable_academic_plan = fields.Boolean(string='Academic Plan')
    enable_create_student_user = fields.Boolean(string='Create Student User')
    enable_exchange_rate_module = fields.Boolean(string='Enable Exchange Rate Synchronization', help='Activate automated exchange rate synchronization capabilities')
    enable_recaptcha = fields.Boolean(string='Enable reCAPTCHA')
    expense_account_id = fields.Many2one('account.account', string='Expense Account', store=False, help='The expense is accounted for when a vendor bill is validated, except in anglo-saxon accounting with perpetual inventory ')
    expense_currency_exchange_account_id = fields.Many2one('account.account', string='Loss Exchange Rate Account', store=False)
    expense_journal_id = fields.Many2one('account.journal', string='Default Expense Journal', store=False, help='The company\'s default journal used when an employee expense is created.')
    external_email_server_default = fields.Boolean(string='Use Custom Email Servers')
    external_report_layout_id = fields.Many2one('ir.ui.view', string='Document Template', store=False)
    fail_counter = fields.Integer(string='Fail Mail', store=False)
    favicon = fields.Binary(string='Favicon', store=False, help='This field holds the image used to display a favicon on the website.')
    fiscalyear_last_day = fields.Integer(string='Fiscalyear Last Day', store=False)
    fiscalyear_last_month = fields.Selection(string='Fiscalyear Last Month', store=False, selection=[])
    fiscalyear_lock_date = fields.Date(string='Global Lock Date', store=False, help='Any entry up to and including that date will be postponed to a later time, in accordance with its journal\'s sequence.')
    force_restrictive_audit_trail = fields.Boolean(string='Forced Audit Trail', store=False)
    global_calendar_user_id = fields.Many2one('res.users', string='Calendar User')
    google_analytics_key = fields.Char(string='Google Analytics Key', store=False)
    google_gmail_client_identifier = fields.Char(string='Gmail Client Id')
    google_gmail_client_secret = fields.Char(string='Gmail Client Secret')
    google_maps_static_api_key = fields.Char(string='Google Maps API key')
    google_maps_static_api_secret = fields.Char(string='Google Maps API secret')
    google_search_console = fields.Char(string='Google Search Console Key', store=False, help='Google key, or Enable to access first reply')
    google_translate_api_key = fields.Char(string='Message Translation API Key', help='A valid Google API key is required to enable message translation. https://cloud.google.com/translate/docs/setup')
    group_analytic_accounting = fields.Boolean(string='Analytic Accounting')
    group_auto_done_setting = fields.Boolean(string='Lock Confirmed Sales')
    group_cash_rounding = fields.Boolean(string='Cash Rounding')
    group_discount_per_so_line = fields.Boolean(string='Discounts')
    group_fiscal_year = fields.Boolean(string='Fiscal Years')
    group_gmc_feed = fields.Boolean(string='Google Merchant Center', store=False)
    group_lot_on_delivery_slip = fields.Boolean(string='Display Lots & Serial Numbers on Delivery Slips')
    group_lot_on_invoice = fields.Boolean(string='Display Lots & Serial Numbers on Invoices')
    group_mass_mailing_campaign = fields.Boolean(string='Mailing Campaigns', help='This is useful if your marketing campaigns are composed of several emails')
    group_multi_currency = fields.Boolean(string='Multi-Currencies', help='Allows to work in a multi currency environment')
    group_multi_website = fields.Boolean(string='Multi-website')
    group_product_price_comparison = fields.Boolean(string='Comparison Price', help='Add a strikethrough price to your /shop and product pages for comparison purposes.It will not be displayed if pricelists')
    group_product_pricelist = fields.Boolean(string='Pricelists')
    group_product_variant = fields.Boolean(string='Variants')
    group_proforma_sales = fields.Boolean(string='Pro-Forma Invoice', help='Allows you to send pro-forma invoice.')
    group_sale_delivery_address = fields.Boolean(string='Customer Addresses')
    group_sale_order_template = fields.Boolean(string='Quotation Templates')
    group_send_reminder = fields.Boolean(string='Receipt Reminder', help='Allow automatically send email to remind your vendor the receipt date')
    group_show_uom_price = fields.Boolean(string='Base Unit Price')
    group_stock_adv_location = fields.Boolean(string='Multi-Step Routes', help='Add and customize route operations to process product moves in your warehouse(s): e.g. unload > quality control > stock ')
    group_stock_lot_print_gs1 = fields.Boolean(string='Print GS1 Barcodes for Lots & Serial Numbers')
    group_stock_multi_locations = fields.Boolean(string='Storage Locations', help='Store products in specific locations of your warehouse (e.g. bins, racks) and to track inventory accordingly.')
    group_stock_production_lot = fields.Boolean(string='Lots & Serial Numbers')
    group_stock_reception_report = fields.Boolean(string='Reception Report')
    group_stock_sign_delivery = fields.Boolean(string='Signature')
    group_stock_tracking_lot = fields.Boolean(string='Packages')
    group_stock_tracking_owner = fields.Boolean(string='Consignment')
    group_uom = fields.Boolean(string='Units of Measure & Packagings')
    group_use_lead = fields.Boolean(string='Leads')
    group_use_recurring_revenues = fields.Boolean(string='Recurring Revenues')
    group_warning_purchase = fields.Boolean(string='Purchase Warnings')
    group_warning_sale = fields.Boolean(string='Sale Order Warnings')
    group_warning_stock = fields.Boolean(string='Warnings for Stock')
    hard_lock_date = fields.Date(string='Hard Lock Date', store=False, help='Any entry up to and including that date will be postponed to a later time, in accordance with its journal sequence. This')
    has_accounting_entries = fields.Boolean(string='Has Accounting Entries', store=False)
    has_chart_of_accounts = fields.Boolean(string='Company has a chart of accounts', store=False)
    has_default_share_image = fields.Boolean(string='Use a image by default for sharing', store=False)
    has_enabled_provider = fields.Boolean(string='Has Enabled Provider', store=False)
    has_google_analytics = fields.Boolean(string='Google Analytics', store=False)
    has_google_search_console = fields.Boolean(string='Google Search Console', store=False)
    has_plausible_shared_key = fields.Boolean(string='Plausible Analytics', store=False)
    horizon_days = fields.Float(string='Replenishment Horizon', store=False, help='Configure your horizon to trigger reordering rules earlier to get                                 a head start on replen')
    hr_expense_alias_domain_id = fields.Many2one('mail.alias.domain', string='Hr Expense Alias Domain', store=False)
    hr_expense_alias_prefix = fields.Char(string='Default Alias Name for Expenses')
    hr_expense_use_mailgateway = fields.Boolean(string='Let your employees record expenses by email')
    hr_presence_control_email = fields.Boolean(string='Based on number of emails sent', store=False)
    hr_presence_control_email_amount = fields.Integer(string='# emails to send', store=False)
    hr_presence_control_ip = fields.Boolean(string='Based on IP Address', store=False)
    hr_presence_control_ip_list = fields.Char(string='Valid IP addresses', store=False)
    hr_presence_control_login = fields.Boolean(string='Based on user status in system', store=False)
    income_account_id = fields.Many2one('account.account', string='Income Account', store=False, help='This account will be used when validating a customer invoice.')
    income_currency_exchange_account_id = fields.Many2one('account.account', string='Gain Exchange Rate Account', store=False)
    incoterm_id = fields.Many2one('account.incoterms', string='Default incoterm', store=False, help='International Commercial Terms are a series of predefined commercial terms used in international transactions.')
    invoice_mail_template_id = fields.Many2one('mail.template', string='Email Template', help='Email sent to the customer once the invoice is available.')
    invoice_terms = fields.Html(string='Terms & Conditions', store=False)
    invoice_terms_html = fields.Html(string='Terms & Conditions as a Web page', store=False)
    is_account_peppol_eligible = fields.Boolean(string='PEPPOL eligible', store=False)
    is_batch_and_subject_constraint = fields.Boolean(string='Batch and Subject Constraint')
    is_batch_constraint = fields.Boolean(string='Batch Constraint')
    is_classroom_constraint = fields.Boolean(string='Classroom Constraint')
    is_faculty_constraint = fields.Boolean(string='Faculty Constraint')
    is_hash_verified = fields.Boolean(string='Is Hash Verified', store=False)
    is_installed_sale = fields.Boolean(string='Is the Sale Module Installed')
    is_mail_sent = fields.Boolean(string='Is Mail Sent', store=False)
    is_membership_multi = fields.Boolean(string='Multi Teams')
    is_newsletter_enabled = fields.Boolean(string='Is Newsletter Enabled')
    is_root_company = fields.Boolean(string='Is Root Company', store=False)
    language_count = fields.Integer(string='Number of Languages', store=False)
    language_ids = fields.Many2many('res.lang', string='Languages')
    lead_enrich_auto = fields.Selection(string='Enrich lead automatically', selection=[])
    lead_mining_in_pipeline = fields.Boolean(string='Create a lead mining request directly from the opportunity pipeline.')
    link_qr_code = fields.Boolean(string='Display Link QR-code', store=False)
    lock_confirmed_po = fields.Boolean(string='Lock Confirmed Orders')
    mass_mailing_mail_server_id = fields.Many2one('ir.mail_server', string='Mail Server')
    mass_mailing_outgoing_mail_server = fields.Boolean(string='Dedicated Server', help='Use a specific mail server in priority. Otherwise Odoo relies on the first outgoing mail server available (based on thei')
    mass_mailing_reports = fields.Boolean(string='24H Stat Mailing Reports', help='Check how well your mailing is doing a day after it has been sent.')
    mass_mailing_split_contact_name = fields.Boolean(string='Split First and Last Name', help='Separate Mailing Contact Names into two fields')
    menu_bg_image = fields.Binary(string='Apps Menu Footer Image', store=False)
    microsoft_outlook_client_identifier = fields.Char(string='Outlook Client Id')
    microsoft_outlook_client_secret = fields.Char(string='Outlook Client Secret')
    module_account_3way_match = fields.Boolean(string='3-way matching: purchases, receptions and bills')
    module_account_accountant = fields.Boolean(string='Accounting')
    module_account_bank_statement_extract = fields.Boolean(string='Bank Statement Digitization')
    module_account_bank_statement_import_qif = fields.Boolean(string='Import .qif files')
    module_account_batch_payment = fields.Boolean(string='Use batch payments', help='This allows you grouping payments into a single batch and eases the reconciliation process. -This installs the account_b')
    module_account_budget = fields.Boolean(string='Budget Management')
    module_account_check_printing = fields.Boolean(string='Allow check printing and deposits')
    module_account_extract = fields.Boolean(string='Document Digitization')
    module_account_inter_company_rules = fields.Boolean(string='Manage Inter Company')
    module_account_intrastat = fields.Boolean(string='Intrastat')
    module_account_invoice_extract = fields.Boolean(string='Invoice Digitization')
    module_account_iso20022 = fields.Boolean(string='SEPA Credit Transfer / ISO20022')
    module_account_payment = fields.Boolean(string='Invoice Online Payment')
    module_account_peppol = fields.Boolean(string='PEPPOL Invoicing')
    module_account_reports = fields.Boolean(string='Dynamic Reports')
    module_account_sepa_direct_debit = fields.Boolean(string='Use SEPA Direct Debit')
    module_auth_ldap = fields.Boolean(string='LDAP Authentication')
    module_auth_oauth = fields.Boolean(string='Use external authentication providers (OAuth)')
    module_auto_database_backup = fields.Boolean(string='Database Backup to Local Server')
    module_auto_database_backup_dropbox = fields.Boolean(string='Database Backup to Dropbox')
    module_auto_database_backup_ftp = fields.Boolean(string='Database Backup to Remote FTP Server')
    module_auto_database_backup_google_drive = fields.Boolean(string='Database Backup to Google Drive')
    module_auto_database_backup_onedrive = fields.Boolean(string='Database Backup to Onedrive')
    module_auto_database_backup_sftp = fields.Boolean(string='Database Backup to Remote SFTP Server')
    module_backend_theme = fields.Boolean(string='Backend Theme')
    module_base_geolocalize = fields.Boolean(string='GeoLocalize')
    module_base_import = fields.Boolean(string='Allow users to import data from CSV/XLS/XLSX/ODS files')
    module_bigbluebutton = fields.Boolean(string='Bigbluebutton Enterprise')
    module_crm_iap_enrich = fields.Boolean(string='Enrich your leads automatically with company data based on their email address.')
    module_crm_iap_mine = fields.Boolean(string='Generate new leads based on their country, industries, size, etc.')
    module_currency_rate_live = fields.Boolean(string='Automatic Currency Rates')
    module_delivery = fields.Boolean(string='Delivery Methods')
    module_delivery_bpost = fields.Boolean(string='bpost Connector')
    module_delivery_dhl = fields.Boolean(string='DHL Express Connector')
    module_delivery_easypost = fields.Boolean(string='Easypost Connector')
    module_delivery_envia = fields.Boolean(string='Envia.com Connector')
    module_delivery_fedex_rest = fields.Boolean(string='FedEx Connector')
    module_delivery_sendcloud = fields.Boolean(string='Sendcloud Connector')
    module_delivery_shiprocket = fields.Boolean(string='Shiprocket Connector')
    module_delivery_starshipit = fields.Boolean(string='Starshipit Connector')
    module_delivery_ups_rest = fields.Boolean(string='UPS Connector')
    module_delivery_usps_rest = fields.Boolean(string='USPS Connector')
    module_event_booth = fields.Boolean(string='Booth Management')
    module_event_sale = fields.Boolean(string='Tickets with Sale')
    module_google_address_autocomplete = fields.Boolean(string='Google Address Autocomplete')
    module_google_calendar = fields.Boolean(string='Allow the users to synchronize their calendar  with Google Calendar')
    module_google_gmail = fields.Boolean(string='Support Gmail Authentication')
    module_google_recaptcha = fields.Boolean(string='reCAPTCHA')
    module_googlemeet = fields.Boolean(string='Google Meet')
    module_helpdesk_elearning = fields.Boolean(string='E-Learning')
    module_helpdesk_forum = fields.Boolean(string='Helpdesk Forum')
    module_helpdesk_project_ext = fields.Boolean(string='Helpdesk project')
    module_hr_attendance = fields.Boolean(string='Based on attendances', store=False)
    module_hr_expense_extract = fields.Boolean(string='Send bills to OCR to generate expenses')
    module_hr_expense_stripe = fields.Boolean(string='Link your stripe issuing account to manage company credit cards for your employees through Odoo')
    module_hr_payroll_expense = fields.Boolean(string='Reimburse Expenses in Payslip')
    module_hr_presence = fields.Boolean(string='Advanced Presence Control')
    module_hr_recruitment_extract = fields.Boolean(string='Send CV to OCR to fill applications')
    module_hr_recruitment_survey = fields.Boolean(string='Interview Forms')
    module_hr_skills = fields.Boolean(string='Skills Management')
    module_loyalty = fields.Boolean(string='Promotions, Coupons, Gift Card & Loyalty Program')
    module_mail_plugin = fields.Boolean(string='Allow integration with the mail plugins')
    module_microsoft_calendar = fields.Boolean(string='Allow the users to synchronize their calendar with Outlook Calendar')
    module_microsoft_outlook = fields.Boolean(string='Support Outlook Authentication')
    module_online_appointment = fields.Boolean(string='Online Appointment Enterprise')
    module_openeducat_achievement_enterprise = fields.Boolean(string='Achievement Enterprise')
    module_openeducat_activity = fields.Boolean(string='Activity')
    module_openeducat_activity_enterprise = fields.Boolean(string='Activity Enterprise')
    module_openeducat_admission = fields.Boolean(string='Admission')
    module_openeducat_admission_enterprise = fields.Boolean(string='Admission Enterprise')
    module_openeducat_admission_grading_bridge = fields.Boolean(string='Admission Grading Bridge')
    module_openeducat_alumni_blog_enterprise = fields.Boolean(string='Alumni Blog Enterprise')
    module_openeducat_alumni_enterprise = fields.Boolean(string='Alumni Enterprise')
    module_openeducat_alumni_event_enterprise = fields.Boolean(string='Alumni Event Enterprise')
    module_openeducat_alumni_job_enterprise = fields.Boolean(string='Alumni Job Enterprise')
    module_openeducat_asset_request_enterprise = fields.Boolean(string='Asset Request Enterprise')
    module_openeducat_assignment = fields.Boolean(string='Assignment')
    module_openeducat_assignment_enterprise = fields.Boolean(string='Assignment Enterprise')
    module_openeducat_assignment_grading_bridge = fields.Boolean(string='Assignment Gradebook Bridge')
    module_openeducat_assignment_grading_enterprise = fields.Boolean(string='Assignment Grading Enterprise')
    module_openeducat_assignment_rubrics = fields.Boolean(string='Assignment Rubrics')
    module_openeducat_attendance = fields.Boolean(string='Attendance')
    module_openeducat_attendance_enterprise = fields.Boolean(string='Attendance Enterprise')
    module_openeducat_attendance_face_recognition = fields.Boolean(string='Attendance Face Recognition')
    module_openeducat_attendance_report_xlsx = fields.Boolean(string='Attendance Xlsx Report')
    module_openeducat_campus_enterprise = fields.Boolean(string='Campus Enterprise')
    module_openeducat_classroom = fields.Boolean(string='Classroom')
    module_openeducat_classroom_enterprise = fields.Boolean(string='Classroom Enterprise')
    module_openeducat_convocation = fields.Boolean(string='Convocation')
    module_openeducat_crm_enterprise = fields.Boolean(string='CRM Enterprise')
    module_openeducat_dashboard_kpi = fields.Boolean(string='Dashboard KPI')
    module_openeducat_digital_library = fields.Boolean(string='Digital Library')
    module_openeducat_discipline = fields.Boolean(string='Discipline Enterprise')
    module_openeducat_dynamic_admission = fields.Boolean(string='Dynamic Admission')
    module_openeducat_event_enterprise = fields.Boolean(string='Event Enterprise')
    module_openeducat_exam = fields.Boolean(string='Exam')
    module_openeducat_exam_enterprise = fields.Boolean(string='Exam Enterprise')
    module_openeducat_exam_gpa_enterprise = fields.Boolean(string='Exam GPA Enterprise')
    module_openeducat_exam_grading_bridge = fields.Boolean(string='Exam Grading Bridge')
    module_openeducat_exam_migration_bridge = fields.Boolean(string='Student Migration Exam Bridge')
    module_openeducat_facility = fields.Boolean(string='Facility')
    module_openeducat_facility_enterprise = fields.Boolean(string='Facility Enterprise')
    module_openeducat_fees = fields.Boolean(string='Fees')
    module_openeducat_fees_parent_bridge = fields.Boolean(string='Fees Parent Bridge')
    module_openeducat_fees_plan = fields.Boolean(string='Fees Plan')
    module_openeducat_grading = fields.Boolean(string='Grading')
    module_openeducat_grading_migration_bridge = fields.Boolean(string='Student Migration Grading Bridge')
    module_openeducat_grievance_enterprise = fields.Boolean(string='Grievance')
    module_openeducat_health_enterprise = fields.Boolean(string='Health Enterprise')
    module_openeducat_jitsi_enterprise = fields.Boolean(string='Jitsi Enterprise')
    module_openeducat_job_enterprise = fields.Boolean(string='Job Enterprise')
    module_openeducat_lesson = fields.Boolean(string='Lesson Enterprise')
    module_openeducat_library = fields.Boolean(string='Library')
    module_openeducat_library_barcode = fields.Boolean(string='Library Barcode Enterprise')
    module_openeducat_library_enterprise = fields.Boolean(string='Library Enterprise')
    module_openeducat_live = fields.Boolean(string='Live Meeting')
    module_openeducat_live_assignment = fields.Boolean(string='Live Meeting Assignment')
    module_openeducat_live_attendance = fields.Boolean(string='Live Meeting Attendance')
    module_openeducat_live_attentiveness = fields.Boolean(string='Live Meeting Attentiveness')
    module_openeducat_lms = fields.Boolean(string='LMS Enterprise')
    module_openeducat_lms_admission = fields.Boolean(string='LMS Admission')
    module_openeducat_lms_blog = fields.Boolean(string='LMS Blog Enterprise')
    module_openeducat_lms_forum = fields.Boolean(string='LMS Forum Enterprise')
    module_openeducat_lms_gamification = fields.Boolean(string='LMS Gamification Enterprise')
    module_openeducat_lms_h5p = fields.Boolean(string='LMS H5P Enterprise')
    module_openeducat_lms_sale = fields.Boolean(string='LMS Sale Enterprise')
    module_openeducat_lms_survey = fields.Boolean(string='LMS Survey Enterprise')
    module_openeducat_mass_subject_registration = fields.Boolean(string='Mass Subject Registration')
    module_openeducat_meeting_enterprise = fields.Boolean(string='Meeting Enterprise')
    module_openeducat_notice_board_enterprise = fields.Boolean(string='Notice Board Enterprise')
    module_openeducat_omr = fields.Boolean(string='OMR')
    module_openeducat_parent = fields.Boolean(string='Parent')
    module_openeducat_parent_enterprise = fields.Boolean(string='Parent Enterprise')
    module_openeducat_placement_enterprise = fields.Boolean(string='Placement Enterprise')
    module_openeducat_placement_job_enterprise = fields.Boolean(string='Placement Job Enterprise')
    module_openeducat_quiz = fields.Boolean(string='Quiz Enterprise')
    module_openeducat_quiz_anti_cheating = fields.Boolean(string='Quiz Anti Cheating')
    module_openeducat_scholarship_enterprise = fields.Boolean(string='Scholarship Enterprise')
    module_openeducat_secure = fields.Boolean(string='Secure QR')
    module_openeducat_skill_enterprise = fields.Boolean(string='Skill Enterprise')
    module_openeducat_skypemeet = fields.Boolean(string='Skype Meet')
    module_openeducat_student_attendance_enterprise = fields.Boolean(string='Student Attendance Kiosk')
    module_openeducat_student_feedback_management = fields.Boolean(string='Student Feedback')
    module_openeducat_student_leave_enterprise = fields.Boolean(string='Student Leave')
    module_openeducat_student_mentor = fields.Boolean(string='Student Mentor')
    module_openeducat_student_progress_enterprise = fields.Boolean(string='Student Progress Enterprise')
    module_openeducat_student_skill_assessment = fields.Boolean(string='Skill Assessment Enterprise')
    module_openeducat_student_withdrawal_mgmt = fields.Boolean(string='Student Withdrawal Management')
    module_openeducat_subject_material_allocation = fields.Boolean(string='Subject Material Allocation')
    module_openeducat_thesis = fields.Boolean(string='Thesis')
    module_openeducat_timetable = fields.Boolean(string='Timetable')
    module_openeducat_timetable_enterprise = fields.Boolean(string='Timetable Enterprise')
    module_openeducat_transportation_enterprise = fields.Boolean(string='Transportation Enterprise')
    module_partner_autocomplete = fields.Boolean(string='Partner Autocomplete')
    module_partnership = fields.Boolean(string='Membership / Partnership')
    module_pos_event = fields.Boolean(string='Tickets with PoS')
    module_product_email_template = fields.Boolean(string='Specific Email')
    module_product_expiry = fields.Boolean(string='Expiration Dates', help='Track following dates on lots & serial numbers: best before, removal, end of life, alert.   Such dates are set automatic')
    module_product_margin = fields.Boolean(string='Allow Product Margin')
    module_purchase_product_matrix = fields.Boolean(string='Purchase Grid Entry')
    module_purchase_requisition = fields.Boolean(string='Purchase Agreements')
    module_quality_control = fields.Boolean(string='Quality')
    module_quality_control_worksheet = fields.Boolean(string='Quality Worksheet')
    module_sale_amazon = fields.Boolean(string='Amazon Sync')
    module_sale_commission = fields.Boolean(string='Commissions')
    module_sale_gelato = fields.Boolean(string='Gelato')
    module_sale_loyalty = fields.Boolean(string='Coupons & Loyalty')
    module_sale_margin = fields.Boolean(string='Margins')
    module_sale_pdf_quote_builder = fields.Boolean(string='PDF Quote builder')
    module_sale_product_matrix = fields.Boolean(string='Sales Grid Entry')
    module_sale_shopee = fields.Boolean(string='Shopee Sync')
    module_sms = fields.Boolean(string='SMS')
    module_snailmail_account = fields.Boolean(string='Snailmail')
    module_stock_barcode = fields.Boolean(string='Barcode Scanner')
    module_stock_barcode_barcodelookup = fields.Boolean(string='Stock Barcode Database')
    module_stock_dropshipping = fields.Boolean(string='Dropshipping')
    module_stock_fleet = fields.Boolean(string='Dispatch Management System')
    module_stock_landed_costs = fields.Boolean(string='Landed Costs', help='Affect landed costs on reception operations and split them among products to update their cost price.')
    module_stock_picking_batch = fields.Boolean(string='Batch, Wave & Cluster Transfers')
    module_stock_sms = fields.Boolean(string='SMS Confirmation')
    module_teams = fields.Boolean(string='Teams')
    module_voip = fields.Boolean(string='Phone')
    module_web_unsplash = fields.Boolean(string='Unsplash Image Library')
    module_website_cf_turnstile = fields.Boolean(string='Cloudflare Turnstile')
    module_website_crm_iap_reveal = fields.Boolean(string='Create Leads/Opportunities from your website's traffic')
    module_website_event_exhibitor = fields.Boolean(string='Advanced Sponsors')
    module_website_event_sale = fields.Boolean(string='Online Ticketing')
    module_website_event_track = fields.Boolean(string='Tracks and Agenda')
    module_website_event_track_live = fields.Boolean(string='Live Mode')
    module_website_event_track_quiz = fields.Boolean(string='Quiz on Tracks')
    module_website_helpdesk_mgmt = fields.Boolean(string='Helpdesk Website')
    module_website_hr_recruitment = fields.Boolean(string='Online Posting')
    module_website_livechat = fields.Boolean(string='Module Website Livechat')
    module_website_sale_autocomplete = fields.Boolean(string='Address Autocomplete')
    module_website_sale_collect = fields.Boolean(string='Click & Collect')
    module_whatsapp_account_templates = fields.Boolean(string='Account Templates')
    module_whatsapp_ecommerce_templates = fields.Boolean(string='Whatsapp Ecommerce Templates')
    module_whatsapp_education_templates = fields.Boolean(string='Education Templates')
    module_whatsapp_other_templates = fields.Boolean(string='Other Templates')
    module_whatsapp_services_templates = fields.Boolean(string='Services Templates')
    module_whatsapp_special_occasions_template = fields.Boolean(string='Special Occasions Templates')
    module_zoom = fields.Boolean(string='Zoom')
    newsletter_id = fields.Many2one('mailing.list', string='Newsletter List', store=False)
    next_execution_timestamp = fields.Datetime(string='Next Execution Time', store=False, help='Scheduled time for the next automatic synchronization')
    onboarding_payment_module = fields.Selection(string='Onboarding Payment Module', store=False, selection=[])
    openeducat_instance_hash_key = fields.Char(string='OpenEducat Instance Hash Key', store=False, help='Instance Hash key is correspondence to instance key which you get in mail.')
    openeducat_instance_hash_msg = fields.Char(string='Instance Hash Key Message', store=False)
    openeducat_instance_key = fields.Char(string='OpenEducat Instance Key', store=False)
    parent_qrcode = fields.Boolean(string='QR Code')
    partner_autocomplete_insufficient_credit = fields.Boolean(string='Insufficient credit', store=False)
    pay_invoices_online = fields.Boolean(string='Pay Invoices Online')
    plausible_shared_key = fields.Char(string='Plausible auth Key', store=False)
    plausible_site = fields.Char(string='Plausible Site (e.g. domain.com)', store=False)
    po_double_validation = fields.Selection(string='Levels of Approvals *', store=False, selection=[], help='Provide a double validation mechanism for purchases')
    po_double_validation_amount = fields.Monetary(string='Minimum Amount', store=False, help='Minimum amount for which a double validation is required')
    po_lock = fields.Selection(string='Purchase Order Modification *', store=False, selection=[], help='Purchase Order Modification used when you want to purchase order editable after confirm')
    po_order_approval = fields.Boolean(string='Purchase Order Approval')
    portal_allow_api_keys = fields.Boolean(string='Customer API Keys', store=False)
    portal_confirmation_pay = fields.Boolean(string='Online Payment', store=False)
    portal_confirmation_sign = fields.Boolean(string='Online Signature', store=False)
    predictive_lead_scoring_field_labels = fields.Char(string='Predictive Lead Scoring Field Labels', store=False)
    predictive_lead_scoring_fields = fields.Many2many('crm.lead.scoring.frequency.field', string='Lead Scoring Frequency Fields')
    predictive_lead_scoring_fields_str = fields.Char(string='Lead Scoring Frequency Fields in String')
    predictive_lead_scoring_start_date = fields.Date(string='Lead Scoring Starting Date', store=False)
    predictive_lead_scoring_start_date_str = fields.Char(string='Lead Scoring Starting Date in String')
    prepayment_percent = fields.Float(string='Prepayment percentage', store=False, help='The percentage of the amount needed to be paid to confirm quotations.')
    preview_ready = fields.Boolean(string='Display preview button', store=False)
    product_volume_volume_in_cubic_feet = fields.Selection(string='Volume unit of measure', selection=[])
    product_weight_in_lbs = fields.Selection(string='Weight unit of measure', selection=[])
    profiling_enabled_until = fields.Datetime(string='Profiling enabled until')
    purchase_lock_date = fields.Date(string='Purchases Lock Date', store=False, help='Any entry up to and including that date will be postponed to a later time, in accordance with its journal sequence. This')
    purchase_tax_id = fields.Many2one('account.tax', string='Default Purchase Tax', store=False)
    qr_code = fields.Boolean(string='Display SEPA QR-code', store=False)
    quick_edit_mode = fields.Selection(string='Quick encoding', store=False, selection=[])
    quotation_validity_days = fields.Integer(string='Default Quotation Validity', store=False, help='Days between quotation proposal and expiration. 0 days means automatic expiration is disabled')
    rate_provider_selection = fields.Selection(string='Exchange Rate Provider', store=False, selection=[], help='Select the financial data provider for exchange rate information')
    recaptcha_min_score = fields.Float(string='Minimum score', help='By default, should be one of 0.1, 0.3, 0.7, 0.9. 1.0 is very likely a good interaction, 0.0 is very likely a bot')
    recaptcha_private_key = fields.Char(string='Secret Key')
    recaptcha_public_key = fields.Char(string='Site Key')
    refresh_token = fields.Char(string='Refresh Token')
    replenish_on_order = fields.Boolean(string='Replenish on Order (MTO)', store=False)
    report_footer = fields.Html(string='Custom Report Footer', store=False, help='Footer text displayed at the bottom of all reports.')
    resource_calendar_id = fields.Many2one('resource.calendar', string='Company Working Hours', store=False)
    restrict_template_rendering = fields.Boolean(string='Restrict Template Rendering', help='Users will still be able to render templates. However only Mail Template Editors will be able to create new dynamic temp')
    restrictive_audit_trail = fields.Boolean(string='Restricted Audit Trail', store=False, help='Enable this option to prevent deletion of journal item related logs')
    sale_lock_date = fields.Date(string='Sales Lock Date', store=False, help='Any entry up to and including that date will be postponed to a later time, in accordance with its journal sequence. This')
    sale_tax_id = fields.Many2one('account.tax', string='Default Sale Tax', store=False)
    salesperson_id = fields.Many2one('res.users', string='Salesperson', store=False)
    salesteam_id = fields.Many2one('crm.team', string='Sales Team', store=False)
    secure_qr_code = fields.Selection(string='Secure Qr Code', selection=[])
    security_lead = fields.Float(string='Security Lead Time', store=False, help='Margin of error for dates promised to customers. Products will be scheduled for procurement and delivery that many days ')
    send_abandoned_cart_email = fields.Boolean(string='Abandoned Email', store=False)
    sfu_server_key = fields.Char(string='SFU Server key', help='Base64 encoded key')
    sfu_server_url = fields.Char(string='SFU Server URL')
    shared_user_account = fields.Boolean(string='Shared Customer Accounts', store=False)
    show_blacklist_buttons = fields.Boolean(string='Blacklist Option when Unsubscribing', help='Allow the recipient to manage themselves their state in the blacklist via the unsubscription page.')
    show_branding_in_footer = fields.Boolean(string='Show Branding In Footer', help='Show branding in footer')
    show_effect = fields.Boolean(string='Show Effect')
    show_line_subtotals_tax_selection = fields.Selection(string='Line Subtotals Tax Display', store=False, selection=[])
    show_sale_receipts = fields.Boolean(string='Sale Receipt')
    snailmail_color = fields.Boolean(string='Print In Color', store=False)
    snailmail_cover = fields.Boolean(string='Add a Cover Page', store=False)
    snailmail_cover_readonly = fields.Boolean(string='Snailmail Cover Readonly', store=False)
    snailmail_duplex = fields.Boolean(string='Print Both sides', store=False)
    social_default_image = fields.Binary(string='Default Social Share Image', store=False, help='If set, replaces the website logo as the default social share image.')
    stock_confirmation_type = fields.Selection(string='Stock Text Validation type', store=False, selection=[])
    stock_move_email_validation = fields.Boolean(string='Email Confirmation picking', store=False)
    stock_sms_confirmation_template_id = fields.Many2one('sms.template', string='SMS Template', store=False, help='SMS sent to the customer once the order is delivered.')
    stock_text_confirmation = fields.Boolean(string='Stock Text Validation with stock move', store=False)
    synchronization_batch_size = fields.Integer(string='Batch Size', store=False, help='Number of currencies processed simultaneously during synchronization')
    synchronization_frequency = fields.Selection(string='Synchronization Frequency', store=False, selection=[], help='Configure automatic synchronization frequency for your organization')
    tax_calculation_rounding_method = fields.Selection(string='Tax calculation rounding method', store=False, selection=[])
    tax_cash_basis_journal_id = fields.Many2one('account.journal', string='Tax Cash Basis Journal', store=False)
    tax_exigibility = fields.Boolean(string='Cash Basis', store=False)
    tax_lock_date = fields.Date(string='Tax Lock Date', store=False, help='Any entry up to and including that date will be postponed to a later time, in accordance with its journal sequence. This')
    tenor_api_key = fields.Char(string='Tenor API key', help='Add a Tenor GIF API key to enable GIFs support. https://developers.google.com/tenor/guides/quickstart#setup')
    terms_type = fields.Selection(string='Terms & Conditions format', store=False, selection=[])
    transfer_account_id = fields.Many2one('account.account', string='Internal Transfer', store=False, help='Intermediary account used when moving from a liquidity account to another.')
    twilio_account_sid = fields.Char(string='Account SID')
    twilio_account_token = fields.Char(string='Account Auth Token')
    unsplash_access_key = fields.Char(string='Access Key')
    unsplash_app_id = fields.Char(string='Application ID')
    use_event_barcode = fields.Boolean(string='Use Event Barcode', help='Enable or Disable Event Barcode functionality.')
    use_google_maps_static_api = fields.Boolean(string='Google Maps static API')
    use_invoice_terms = fields.Boolean(string='Default Terms & Conditions')
    use_project = fields.Boolean(string='Use Projects')
    use_security_lead = fields.Boolean(string='Security Lead Time for Sales', help='Margin of error for dates promised to customers. Products will be scheduled for delivery that many days earlier than the')
    use_sfu_server = fields.Boolean(string='Use SFU server', help='If you want to setup SFU server for large group calls.')
    use_twilio_rtc_servers = fields.Boolean(string='Use Twilio ICE servers', help='If you want to use twilio as TURN/STUN server provider')
    use_website_form = fields.Boolean(string='Website Form')
    verify_date = fields.Char(string='Verify Date', store=False)
    web_app_name = fields.Char(string='Web App Name')
    website_block_third_party_domains = fields.Boolean(string='Block 3rd-party domains', store=False, help='Block 3rd-party domains that may track users (YouTube, Google Maps, etc.).')
    website_company_id = fields.Many2one('res.company', string='Website Company', store=False)
    website_cookies_bar = fields.Boolean(string='Cookies Bar', store=False, help='Display a customizable cookies bar on your website.')
    website_default_lang_code = fields.Char(string='Default language code', store=False, help='This field is used to set/get locales for user')
    website_default_lang_id = fields.Many2one('res.lang', string='Default language', store=False)
    website_domain = fields.Char(string='Website Domain', store=False, help='E.g. https://www.mydomain.com')
    website_homepage_url = fields.Char(string='Homepage Url', store=False, help='E.g. /contactus or /shop')
    website_id = fields.Many2one('website', string='website')
    website_language_count = fields.Integer(string='Number of languages', store=False)
    website_logo = fields.Binary(string='Website Logo', store=False, help='Display this logo on the website.')
    website_name = fields.Char(string='Website Name', store=False)
    website_sale_contact_us_button_url = fields.Char(string='Button Url', store=False)
    website_sale_prevent_zero_price_sale = fields.Boolean(string='Prevent Sale of Zero Priced Product', store=False)
    website_warehouse_id = fields.Many2one('stock.warehouse', string='Warehouse', store=False)
    whatsapp_business_id = fields.Many2one('whatsapp.business', string='Business Account')
    work_permit_expiration_notice_period = fields.Integer(string='Work Permit Expiry Notice Period', store=False)

    # Mixin-inherited fields (not redeclared): create_date, create_uid, display_name, id, write_date, write_uid

    # Access Rights:
    #   Role / Administrator: read, write, create

    # ── Computed / onchange methods (reconstructed stubs) ───────────

    @api.depends()  # TODO: add real dependencies
    def _compute_account_cash_basis_base_account_id(self):
        for rec in self:
            rec.account_cash_basis_base_account_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_default_credit_limit(self):
        for rec in self:
            rec.account_default_credit_limit = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_discount_expense_allocation_id(self):
        for rec in self:
            rec.account_discount_expense_allocation_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_discount_income_allocation_id(self):
        for rec in self:
            rec.account_discount_income_allocation_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_fiscal_country_id(self):
        for rec in self:
            rec.account_fiscal_country_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_journal_early_pay_discount_gain_account_id(self):
        for rec in self:
            rec.account_journal_early_pay_discount_gain_account_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_journal_early_pay_discount_loss_account_id(self):
        for rec in self:
            rec.account_journal_early_pay_discount_loss_account_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_journal_suspense_account_id(self):
        for rec in self:
            rec.account_journal_suspense_account_id = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_on_checkout(self):
        for rec in self:
            rec.account_on_checkout = False  # TODO: implement

    @api.depends()  # TODO: add real dependencies
    def _compute_account_price_include(self):
        for rec in self:
            rec.account_price_include = False  # TODO: implement

    # ── CRUD overrides (if any) ──────────────────────────────────────

    # def create(self, vals):
    #     return super().create(vals)

    # def write(self, vals):
    #     return super().write(vals)

    # ── Business logic ───────────────────────────────────────────────

    # TODO: add action methods found in ir.actions.server for this model
